apiVersion: v1
name: fission-workflows
version: 0.7.0
appVersion: 0.7.0
description: Fission Workflows is a fast workflow engine for serverless functions on Kubernetes
keywords:
- fission
- serverless
- workflows
- coordination
- orchestration
- function-as-a-service
home: http://fission.io/
sources:
  - https://github.com/fission/fission-workflows
maintainers:
  - name: Erwin van Eyk
    email: erwin@platform9.com
  - name: Soam Vasani
    email: soamvasani@platform9.com
engine: gotpl
