#
# Fission Workflows chart configuration
#

# Bundle image
bundleImage: fission/fission-workflows-bundle:0.1.2

# Image of the Fission environment for Fission Workflows
envImage: fission/workflow-env:0.1.2

# Image of the Fission build environment for Fission Workflows
buildEnvImage: fission/workflow-build-env:0.1.2

# Deploy optional Workflow api-server?
apiserver: true

# Fission configuration
fnenv:
  fission:
    controller: http://controller.fission
    poolmgr: http://poolmgr.fission

# Message queue config
nats:
  authToken: defaultFissionAuthToken
  cluster: fissionMQTrigger
  location: nats-streaming:4222
