#
# Fission Workflows chart configuration
#

# Basic settings
name: workflows
bundleImage: fission/fission-workflows-bundle
tag: 0.6.0
pullPolicy: IfNotPresent
debug: false

service:
  name: workflows
  type: ClusterIP
  ports:
    grpc: 5555
    http: 80

# Event store-related configuration
eventstore:
  type: mem # supported: nats, mem
  nats:
    authToken: defaultFissionAuthToken
    cluster: fissionMQTrigger
    location: nats-streaming
    port: 4222

# Fission-related configuration
fission:
  ns: fission
  controller: http://controller
  executor: http://executor
  env:
    name: workflow
    ns: default
    runtimeImage: fission/fission-workflows-proxy
    builderImage: fission/workflow-build-env

# Tracing-related configuration
jaeger:
  collector: jaeger-collector:14267