#
# Fission Workflows chart configuration
#

# Bundle image
bundleImage: fission/fission-workflows-bundle

# Image of the Fission environment for Fission Workflows
envImage: fission/workflow-env

# Image of the Fission build environment for Fission Workflows
buildEnvImage: fission/workflow-build-env

tag: 0.3.0

pullPolicy: IfNotPresent

# Deploy optional Workflow api-server?
apiserver: true

# Fission configuration
fnenv:
  fission:
    ns: fission
    controller: http://controller
    executor: http://executor

# Message queue config
nats:
  authToken: defaultFissionAuthToken
  cluster: fissionMQTrigger
  location: nats-streaming
  port: 4222
